title: Zhuohoudeputao
baseurl: ""
url: ""
markdown: kramdown
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
# Exclude vendor/bundle and other non-site directories
exclude:
  - my_bundle/
  - vendor/
  - .bundle/
  - node_modules/
  - .git/
  - .gitignore